name: Build APK
on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Build APK
        uses: egoholic/buildozer-action@v1
        with:
          buildozer_version: stable
          buildozer_target: android debug
          
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: WYC-MPESA-APK
          path: bin/*.apk
